### ISSUE TITLE
oidc signin: TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#137]
#### Description
**Is**:
If client has network access to server but for some reason not to `oidc.providerUrl`, oidc.signin throws an uncaught TypeError:

```
INFO <main> [startup]: requested oidc signin ({"idp":{"provider":"tam","clientId":"xxx","clientSecret":"xxx","providerUrl":"xxx","redirectUri":"http://127.0.0.1:13006","scope":"openid profile offline_access","imgBase64":"xxx"}})
ERROR <main> [main]: uncaught exception ({
  "error": {
    "stack":"TypeError: Cannot read property 'statusCode' of undefined
      at Request._callback (balloon-client-desktop/node_modules/@openid/appauth/src/node_support/node_requestor.ts:35:26)
      at self.callback (balloon-client-desktop/node_modules/request/request.js:186:22)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.onRequestError (balloon-client-desktop/node_modules/request/request.js:878:8)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at TLSSocket.socketErrorListener (_http_client.js:387:9)
      at emitOne (events.js:116:13)
      at TLSSocket.emit (events.js:211:7)","message":"Cannot read property 'statusCode' of undefined"
  }
})
```

**Should**:
Error should be caught, and user informed, that login was not success full.

#### balloon desktop version
0.2.3

#### Your client operating system
N/A

#### Filesystem (If known)
N/A

#### balloon server version (If known)
N/A

**Comment by pixtron** [comment]
With appauth@1.1.1 this now leads to: 

```
AppAuthError {
  message:
   'Error: connect EHOSTDOWN x.x.x.x:443 - Local (0.0.0.0:0)',
  extras: undefined }
```
