### ISSUE TITLE
Main: uncaught exception","stack":"Error: Cannot find module 'C:\\Program Files\\Balloon\\resources\\app.asar\\app\\i18n\\en-US.json

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#18]
`{"message":"Main: uncaught exception","stack":"Error: Cannot find module 'C:\\Program Files\\Balloon\\resources\\app.asar\\app\\i18n\\en-US.json'\n    at Module._resolveFilename (module.js:470:15)\n    at Function.Module._resolveFilename (C:\\Program Files\\Balloon\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)\n    at Function.Module._load (module.js:418:25)\n    at Module.require (module.js:498:17)\n    at require (internal/module.js:20:19)\n    at changeLanguage (C:\\Program Files\\Balloon\\resources\\app.asar\\app\\lib\\i18n.js:30:18)\n    at App.<anonymous> (C:\\Program Files\\Balloon\\resources\\app.asar\\app\\lib\\i18n.js:48:5)\n    at emitTwo (events.js:111:20)\n    at App.emit (events.js:194:7)","code":"MODULE_NOT_FOUND","level":"error","timestamp":"2017-09-28T11:48:32.044Z"}`

#### balloon desktop version
0.0.30

#### Your client operating system
Windows 10

#### Filesystem (If known)
NTFS

**Comment by raffis** [comment]
Not relevant anymore.
