### ISSUE TITLE
Two Factor authentication

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-desktop#186]
Upcoming balloon v2.5.x has an integrated Idp and supports two factor auth via google authenticator, see gyselroth/balloon#242 and gyselroth/balloon#285

Should:
Integrate support for oauth flows password and password_mfa grant flows. Add new config: credentials which can either be null (no credentials login), "token" (oauth2 first party authentication) or "basic" (HTTP basic authentication).

Todos:
Implement auth via token auth POST /api/v2/tokens (first party auth grant types)
Add input for token if grant_type password_mfa

gyselroth/balloon-client-web#141

**Comment by raffis** [comment]
@pixtron This ends in an error (each time):

```
DEBUG <main> [startup]: verify that balloonDir exists
DEBUG <main> [autolaunch]: verify that autolaunch has correct state
DEBUG <main> [autolaunch]: trying to enable autolaunch
DEBUG <main> [startup]: skip startup authentication, first time wizard needs to be executed first
INFO <main> [startup]: start first time wizard
INFO <main> [startup]: first time wizard unlinked active instance
INFO <main> [auth]: logout initialized ({})
INFO <main> [auth]: Destroying secrets ({"excludeRefreshToken":false})
DEBUG <main> [startup]: startup window opened
DEBUG <main> [autolaunch]: autolaunch already enabled. Skip enable
INFO <1> [tray-browser]: got config ({"secretType":null})
INFO <1> [tray-browser]: updateWindow
INFO <1> [tray-browser]: loadMenu ({"menu":"status"})
INFO <1> [tray-browser]: got config ({"secretType":null})
INFO <1> [tray-browser]: updateWindow
INFO <1> [tray-browser]: loadMenu ({"menu":"status"})
INFO <main> [startup]: change url to server ({"url":"https://localhost:8081"})
DEBUG <main> [startup]: ask user for authentication credentials
DEBUG <main> [startup]: waiting for user action
DEBUG <main> [startup]: startup window opened
INFO <main> [startup]: requested credentials authentication ({"username":"admin"})
INFO <main> [auth]: Do token auth ({"username":"admin","grant_type":"password"})
INFO <1> [tray-browser]: got config ({"secretType":"accessToken"})
INFO <1> [tray-browser]: updateWindow
INFO <1> [tray-browser]: loadMenu ({"menu":"status"})
INFO <1> [tray-browser]: template loaded ({"menu":"status"})
DEBUG <main> [auth]: Stored tokens
ERROR <main> [auth]: failed signin via token auth ({"error":{"stack":"BlnConfigError: Neither accessToken nor username/password set\n    at getAuthorizationHeader (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:42:11)\n    at getReqOptions (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:68:24)\n    at Object.sendRequest (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:160:22)\n    at Object.whoami (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api.js:65:19)\n    at /home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:484:19\n    at new Promise (<anonymous>)\n    at verifyNewLogin (/home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:479:12)\n    at _storeAuthTokens.then (/home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:159:17)\n    at <anonymous>","name":"BlnConfigError","message":"Neither accessToken nor username/password set","code":"E_BLN_CONFIG_CREDENTIALS"}})
ERROR <main> [startup]: Credentials auth resulted in an error ({"error":{"stack":"BlnConfigError: Neither accessToken nor username/password set\n    at getAuthorizationHeader (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:42:11)\n    at getReqOptions (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:68:24)\n    at Object.sendRequest (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api-request.js:160:22)\n    at Object.whoami (/home/raffael/dev/balloon/balloon-node-sync/lib/bln-api.js:65:19)\n    at /home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:484:19\n    at new Promise (<anonymous>)\n    at verifyNewLogin (/home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:479:12)\n    at _storeAuthTokens.then (/home/raffael/dev/balloon/balloon-client-desktop/app/lib/auth/controller.js:159:17)\n    at <anonymous>","name":"BlnConfigError","message":"Neither accessToken nor username/password set","code":"E_BLN_CONFIG_CREDENTIALS"}})
```

**Comment by raffis** [comment]
never mind, forgot to update the sync lib.
