### ISSUE TITLE
Do not unlink account if access token can not get refreshed

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#188]
#### Describe the bug
the desktop client unlinks the account if an access token can not be refreshed via external idp.

#### To Reproduce
Authenticated via external OpenID-connect idp.

#### Expected behavior
No unlink if the request ends in certain http response codes.  For example do not unlink during a ETIMEDOUT.

#### Environment
 - desktop client version: v1.0.0
 - balloon server version: v2.4.4
 - client os: [e.g. Linux Mint 19.2]
 - client cpu architecture: [e.g. amd64]
 - filesystem: [e.g. ntfs (Where the balloon folder is located)]

#### Additional context
```
2019-04-03 14:05:04 INFO <main> [unknown]: API: GET request to /node/delta with params:  ({"attributes":["parent","hash","version","size"],"limit":1,"cursor":"ZGVsdGF8MHwwfDVjYTQ5ZjYzOGY3Njg4MGYyYzNjMWRjOXwxNTU0MjkyNTc5MTU4"})
2019-04-03 14:05:08 WARNING <main> [unknown]: API: Got Status Code 401 Unauthorized
2019-04-03 14:05:08 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:08 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:08 INFO <main> [sync.watcher]: stoping watcher ({"paused":false})
2019-04-03 14:05:08 DEBUG <main> [sync.watcher.local]: local watcher stop requested ({"state":2})
2019-04-03 14:05:08 DEBUG <main> [sync.watcher.local]: nfswWatcher stop requested
2019-04-03 14:05:08 INFO <main> [sync.watcher]: remote watcher stoped ({"paused":false})
2019-04-03 14:05:08 DEBUG <main> [main]: got 401, refresh accessToken
2019-04-03 14:05:08 DEBUG <main> [sync.watcher.local]: nfswWatcher stopped
2019-04-03 14:05:08 INFO <main> [sync.watcher]: local watcher stoped ({"paused":false})
2019-04-03 14:05:09 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:162:22)\n    at self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at ClientRequest.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at ClientRequest.emit (events.js:208:7)\n    at TLSSocket.emitTimeout (_http_client.js:708:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket.Socket._onTimeout (net.js:407:8)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"code":"ESOCKETTIMEDOUT","connect":false}}})
2019-04-03 14:05:09 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:162:22)\n    at self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at ClientRequest.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at ClientRequest.emit (events.js:208:7)\n    at TLSSocket.emitTimeout (_http_client.js:708:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket.Socket._onTimeout (net.js:407:8)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"code":"ESOCKETTIMEDOUT","connect":false}}})
2019-04-03 14:05:11 WARNING <main> [unknown]: API: Got Status Code 401 Unauthorized
2019-04-03 14:05:11 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:11 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:14 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:162:22)\n    at self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at ClientRequest.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at ClientRequest.emit (events.js:208:7)\n    at TLSSocket.emitTimeout (_http_client.js:708:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket.Socket._onTimeout (net.js:407:8)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"code":"ESOCKETTIMEDOUT","connect":false}}})
2019-04-03 14:05:14 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:162:22)\n    at self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at ClientRequest.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at ClientRequest.emit (events.js:208:7)\n    at TLSSocket.emitTimeout (_http_client.js:708:34)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket.Socket._onTimeout (net.js:407:8)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"code":"ESOCKETTIMEDOUT","connect":false}}})
2019-04-03 14:05:17 WARNING <main> [unknown]: API: Got Status Code 401 Unauthorized
2019-04-03 14:05:17 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:17 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:17 WARNING <main> [unknown]: API: Got Status Code 401 Unauthorized
2019-04-03 14:05:17 ERROR <main> [watcher]: Remote watcher had error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:05:17 ERROR <main> [sync]: Watcher error ({"err":{"stack":"BlnWatcherError: Recievieng node delta had error\n    at blnApi.nodeDelta (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/watcher/remote-factory.js:41:25)\n    at blnApiRequest.sendRequest (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api.js:459:22)\n    at handleResponse (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:104:12)\n    at Request.request [as _callback] (/opt/Balloon/resources/app.asar/node_modules/@gyselroth/balloon-node-sync/lib/bln-api-request.js:163:7)\n    at Request.self.callback (/opt/Balloon/resources/app.asar/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/opt/Balloon/resources/app.asar/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1056:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"BlnWatcherError","message":"Recievieng node delta had error","code":"E_BLN_REMOTE_WATCHER_DELTA","origErr":{"name":"BlnApiRequestError","message":"User is not authenticated","code":"E_BLN_API_REQUEST_UNAUTHORIZED"}}})
2019-04-03 14:07:18 ERROR <main> [openid-connect]: Could not fetch service configuration ({"err":{"message":"Error: connect ETIMEDOUT 192.168.100.163:443"}})
2019-04-03 14:07:18 ERROR <main> [main]: could not refresh accessToken, unlink instance ({"err":{"message":"Error: connect ETIMEDOUT 192.168.100.163:443"}})
2019-04-03 14:07:18 INFO <main> [unknown]: Sync: pause requested
```

**Comment by pixtron** [comment]
Closing this issue as the fixes have been published with v1.2.0
