### ISSUE TITLE
app quits right after start

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#69]
#### Description
**Is**:
`{"category":"bootstrap","state":true,"level":"info","message":"initial online state","timestamp":"2017-12-19T13:24:57.418Z"}
{"category":"startup","level":"debug","message":"verify that balloonDir exists","timestamp":"2017-12-19T13:24:57.419Z"}
{"category":"startup","level":"debug","message":"verify that autolaunch is enabled","timestamp":"2017-12-19T13:24:57.419Z"}
{"category":"startup","level":"debug","message":"verify authentication","timestamp":"2017-12-19T13:24:57.429Z"}
{"category":"auth","level":"info","message":"login initialized","timestamp":"2017-12-19T13:24:57.430Z"}
{"category":"auth","level":"error","message":"can not verify credentials, no secret available","timestamp":"2017-12-19T13:24:57.430Z"}
{"category":"auth","authMethod":"basic","username“:“username“,“level":"info","message":"verify authentication via whoami api call","timestamp":"2017-12-19T13:24:57.431Z"}
{"level":"info","message":"API: GET request to /user/whoami with params: ","timestamp":"2017-12-19T13:24:57.432Z"}
{"category":"auth","error":{"stack":"Error: Secret not set\n    at /Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:225:16\n    at Promise (<anonymous>)\n    at verifyAuthentication (/Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:220:12)\n    at /Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:169:7\n    at Promise (<anonymous>)\n    at Object.login (/Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:168:12)\n    at /Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:142:12\n    at Promise (<anonymous>)\n    at authenticate (/Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:140:12)\n    at Object.checkConfig (/Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:68:7)\n    at EventEmitter.<anonymous> (/Users/testuser/dev/balloon-client-desktop/app/main.js:61:15)\n    at Object.onceWrapper (events.js:293:19)\n    at emitTwo (events.js:111:20)\n    at EventEmitter.emit (events.js:194:7)\n    at WebContents.<anonymous> (/Users/testuser/dev/balloon-client-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)\n    at emitTwo (events.js:106:13)","message":"Secret not set"},"level":"info","message":"login failed","timestamp":"2017-12-19T13:24:57.441Z"}
{"category":"bootstrap","error":{"stack":"Error: Secret not set\n    at /Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:225:16\n    at Promise (<anonymous>)\n    at verifyAuthentication (/Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:220:12)\n    at /Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:169:7\n    at Promise (<anonymous>)\n    at Object.login (/Users/testuser/dev/balloon-client-desktop/app/lib/auth/controller.js:168:12)\n    at /Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:142:12\n    at Promise (<anonymous>)\n    at authenticate (/Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:140:12)\n    at Object.checkConfig (/Users/testuser/dev/balloon-client-desktop/app/ui/startup/controller.js:68:7)\n    at EventEmitter.<anonymous> (/Users/testuser/dev/balloon-client-desktop/app/main.js:61:15)\n    at Object.onceWrapper (events.js:293:19)\n    at emitTwo (events.js:111:20)\n    at EventEmitter.emit (events.js:194:7)\n    at WebContents.<anonymous> (/Users/testuser/dev/balloon-client-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)\n    at emitTwo (events.js:106:13)","message":"Secret not set"},"level":"error","message":"startup checkconfig","timestamp":"2017-12-19T13:24:57.441Z"}`

**Should**:
auth window should pop up

#### balloon desktop version
0.0.37

#### Your client operating system
OS X

**Comment by raffis** [comment]
@pixtron tbd
https://github.com/gyselroth/balloon-client-desktop/blob/master/app/lib/auth/controller.js#L175
https://github.com/gyselroth/balloon-client-desktop/blob/master/app/lib/auth/controller.js#L225
https://github.com/gyselroth/balloon-client-desktop/blob/master/app/main.js#L105
